Add Slack announcement when build run on main fails (#12521)
* Add Slack announcement when scheduled test run fails

changelog: Internal, Testing, Add Slack announcement when scheduled test run fails

* Update test coverage dependencies

* fix notification

* always run coverage

* updates to run for any test failures on main

* Update .gitlab-ci.yml

Co-authored-by: Shane Chesnutt <shane.chesnutt@gsa.gov>

* add comment

---------

Co-authored-by: Shane Chesnutt <shane.chesnutt@gsa.gov>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -382,6 +382,38 @@ coverage:
       - coverage/index.html
       - coverage/assets/
       - coverage/coverage.xml
+  when: always
+
+# This job posts a message in Slack if the `spec` job fails for a commit on main.
+# We use artifacts from the merged rspec report to read the number of failed jobs to check
+# whether the tests all passed.
+# This must be a separate job because the tests run in parallel and there is no way to run
+# a single job based on the result of all of them.
+alert_main_test:
+  stage: after_test
+  needs:
+    - job: coverage
+  cache:
+    - <<: *ruby_cache
+  script:
+    - *bundle_install
+    - |-
+      cat rspec_json/rspec.json | ruby -rjson -e 'failure_count = JSON.parse(ARGF.read).fetch("summary").fetch("failure_count"); exit 1 if failure_count > 0'
+  after_script:
+    - |-
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        ./scripts/notify-slack \
+          --icon ":gitlab:"  \
+          --username "gitlab-notify" \
+          --channel "#login-appdev" \
+          --webhook "${SLACK_WEBHOOK}" \
+          --raise \
+          --text "$(printf "Pipeline failed for branch:${CI_COMMIT_BRANCH} in GitLab.\nBuild Results: ${CI_JOB_URL}.")"
+      else
+        echo "Not notifying in slack"
+      fi
+  rules:
+    - if: $CI_COMMIT_BRANCH == "main"
 
 build-ci-image:
   stage: build
