fix notification

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -296,19 +296,6 @@ specs:
     - bundle exec rake db:create db:migrate --trace
     - bundle exec rake db:seed
     - bundle exec rake knapsack:rspec["--format documentation --format RspecJunitFormatter --out rspec.xml --format json --out rspec_json/${CI_NODE_INDEX}.json"]
-  after_script:
-    - |-
-      if [ "$CI_JOB_STATUS" != "success" ] && [ "$CI_PIPELINE_SOURCE" == "schedule" ]; then
-        ./scripts/notify-slack \
-          --icon ":gitlab:"  \
-          --username "gitlab-notify" \
-          --channel "#login-appdev" \
-          --webhook "${SLACK_WEBHOOK}" \
-          --raise \
-          --text "$(printf "A scheduled test run failed in GitLab.\nBuild Results: ${CI_JOB_URL}.")"
-      else
-        echo "Not notifying in slack"
-      fi
 
 lint:
   stage: test
@@ -395,6 +382,35 @@ coverage:
       - coverage/index.html
       - coverage/assets/
       - coverage/coverage.xml
+
+# This job posts a message in Slack if the `spec` job fails during a scheduled run.
+# This must be a separate job because the tests run in parallel and there is no way to run
+# a single job based on the result of all of them.
+test_scheduled:
+  stage: after_test
+  needs:
+    - job: coverage
+  cache:
+    - <<: *ruby_cache
+  script:
+    - *bundle_install
+    - |-
+      cat rspec_json/rspec.json | ruby -rjson -e 'failure_count = JSON.parse(ARGF.read).fetch("summary").fetch("failure_count"); exit 1 if failure_count > 0'
+  after_script:
+    - |-
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        ./scripts/notify-slack \
+          --icon ":gitlab:"  \
+          --username "gitlab-notify" \
+          --channel "#login-appdev" \
+          --webhook "${SLACK_WEBHOOK}" \
+          --raise \
+          --text "$(printf "A scheduled test run failed in GitLab.\nBuild Results: ${CI_JOB_URL}.")"
+      else
+        echo "Not notifying in slack"
+      fi
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "main"
 
 build-ci-image:
   stage: build
