Deploy script updates for local execution (#9929)
* Update scripts/create-deploy-pr

- Support $GITHUB_REPOSITORY to specify the repository.
- Only check $GH_TOKEN present when running in CI
- Figure out $GITHUB_SHA automatically when running locally
- Use tmp/ for temporary files

* Update scripts/create-release

- Allow running locally while still verifying prereqs present in CI
- Add DRY_RUN support to prevent making changes while testing
- Use tmp/ for temporary files
- Support $GITHUB_REPOSITORY to specify which repo to use

* Say GIT_REMOTE instead of ORIGIN

* create-deploy-pr: Add FORMAT_CHANGELOG env

Allow specifying a command to pipe changelog to for additional formatting

* create-deploy-pr: create label if it does not exist

* create-deploy-pr: don't die if no releases found

* create-deploy-pr: Clean up output a little

* create-deploy-pr: Convert git remote URLs to lowercase

* Remove Github Actions workflows for now

* Use $GH_REPO instead of $GITHUB_REPOSITORY

gh recognizes $GH_REPO and will use it so you don't always have to specify --repo

* changelog: Internal, Deployment, Add local scripts to help with deployment

diff --git a/scripts/create-release b/scripts/create-release
--- a/scripts/create-release
+++ b/scripts/create-release
@@ -3,8 +3,10 @@
 set -euo pipefail
 
 DEPLOY_BRANCH=stages/prod
-PR_JSON_FILE=${PR_JSON_FILE:-.pr.json}
-CHANGELOG_FILE=${CHANGELOG_FILE:-.changelog.md}
+DRY_RUN=${DRY_RUN:-0}
+PR_JSON_FILE=${PR_JSON_FILE:-tmp/.pr.json}
+CHANGELOG_FILE=${CHANGELOG_FILE:-tmp/.changelog.md}
+GH_REPO=${GH_REPO:-18f/identity-idp}
 
 USAGE="
 ${0} [PULL_REQUEST_NUMBER]
@@ -13,33 +15,52 @@ Creates a new release based on the given PR having been merged.
 "
 
 if [ $# -eq 0 ]; then
-    echo $USAGE
+    echo "$USAGE"
     exit 1
 fi
 
 PR="$1"; shift
 
-if [ -z "${CI:-}" ]; then
-    echo "This script is meant to be run in a continuous integration environment."
+if ! which gh > /dev/null 2>&1; then
+    echo "Github CLI (gh) is not installed. You can install it with: brew install gh"
     exit 1
 fi
 
-if [ -z "${GH_TOKEN:-}" ]; then
-    echo "You must set the GH_TOKEN environment variable."
-    exit 1
+if [ "${CI:-}" == "1" ]; then
+    # gh will not work in CI unless GH_TOKEN is explicitly set.
+    if [ -z "${GH_TOKEN:-}" ]; then
+        echo "You must set the GH_TOKEN environment variable."
+        exit 1
+    fi
+
+    # GITHUB_SHA is provided by Github Actions, but if for some reason
+    # you are running locally with CI=1 trying to simulate a CI run,
+    # make it clear that we want it set.
+    if [ -z "${GITHUB_SHA:-}" ]; then
+        echo "\$GITHUB_SHA must be set."
+        exit 1
+    fi
 fi
 
+mkdir -p "$(dirname "$PR_JSON_FILE")" || true
+mkdir -p "$(dirname "$CHANGELOG_FILE")" || true
 
 echo "Getting PR ${PR} data..."
 gh pr list \
-    --json number,title,body \
+    --json number,mergeCommit,title,body \
     --base "$DEPLOY_BRANCH" \
     --state merged \
-    jq ".[] | select(.number == ${PR})" > "$PR_JSON_FILE"
+    | jq ".[] | select(.number == ${PR})" > "$PR_JSON_FILE"
 
 if [ ! -s "$PR_JSON_FILE" ]; then
-    echo "PR $PR not found."
+    echo "Merged PR $PR not found."
     exit 9
+fi
+
+if [ -z "${GITHUB_SHA:-}" ]; then
+    # $GITHUB_SHA is set by Github Actions. But when running locally we can
+    # pull it out of the PR's JSON blob.
+    GITHUB_SHA=$(jq --raw-output '.mergeCommit.oid' < "$PR_JSON_FILE")
 fi
 
 RC=$(jq --raw-output '.title' < "$PR_JSON_FILE" | sed -E 's/Deploy RC (.+) to .*/\1/')
@@ -49,7 +70,7 @@ TITLE="RC $RC"
 echo "Checking for existing release '$TITLE'..."
 EXISTING_RELEASE=$(gh release list --exclude-drafts | (grep "$TITLE" || true))
 
-if [ ! -z "$EXISTING_RELEASE" ]; then
+if [ -n "$EXISTING_RELEASE" ]; then
     echo "❌ Release already exists: $TITLE" >&2
     exit 10
 else
@@ -58,10 +79,14 @@ fi
 
 TAG=$(date -u +'%Y-%m-%dT%H%M%S')
 
-echo "Creating release $TITLE with tag $TAG..."
-gh release create \
-    "$TAG" \
-    --latest \
-    --target "$GITHUB_SHA" \
-    --title "$TITLE" \
-    --notes-file "$CHANGELOG_FILE"
+if [ "${DRY_RUN:-}" == "1" ]; then
+    echo "Dry run. Not creating release $TITLE with tag $TAG ($GITHUB_SHA)..."
+else
+    echo "Creating release $TITLE with tag $TAG..."
+    gh release create \
+        "$TAG" \
+        --latest \
+        --target "$GITHUB_SHA" \
+        --title "$TITLE" \
+        --notes-file "$CHANGELOG_FILE"
+fi
