Support patch deploys

diff --git a/scripts/create-deploy-pr b/scripts/create-deploy-pr
--- a/scripts/create-deploy-pr
+++ b/scripts/create-deploy-pr
@@ -3,6 +3,7 @@
 set -euo pipefail
 
 ORIGIN=${ORIGIN:-origin}
+SOURCE=${SOURCE:-}
 DEPLOY_BRANCH=stages/prod
 PATCH=${PATCH:-}
 DRY_RUN=${DRY_RUN:-0}
@@ -13,11 +14,6 @@ do
     case "$1" in
         --dry-run)
             DRY_RUN=1
-            shift
-            ;;
-
-        --patch)
-            PATCH=1
             shift
             ;;
 
@@ -45,9 +41,8 @@ function get_last_rc {
 
 function get_next_rc {
     LAST_RC="$1"; shift
-    
     MAJOR=$(echo "$LAST_RC" | sed -E 's/\.[0-9]+//')
-    MINOR=$(echo "$LAST_RC" | sed -E 's/[0-9]+\.//')
+    MINOR=$(echo "$LAST_RC" | sed -E 's/[0-9]+(\.|$)//')
     
     if [ "$PATCH" == "1" ]; then
         # Doing a patch, so increment minor version by 1
@@ -78,7 +73,7 @@ if [ -z "${CI:-}" ]; then
     exit 1
 fi
 
-if [ -z "${GH_TOKEN:-}" ]; then
+if [ -z "${GH_TOKEN:-}" ] && [ "$DRY_RUN" == "0" ]; then
     echo "You must set the GH_TOKEN environment variable."
     exit 1
 fi
@@ -87,8 +82,21 @@ LAST_RC=$(get_last_rc)
 NEXT_RC=$(get_next_rc "$LAST_RC")
 echo "Last RC was ${LAST_RC}. The next RC will be ${NEXT_RC}."
 
-SHA=$(get_staging_sha)
-echo "Staging currently running ${SHA}"
+if [ -z "$SOURCE" ]; then
+    SHA=$(get_staging_sha)
+    echo "Staging currently running ${SHA}"
+else
+    SHA=$(git rev-parse "$SOURCE" || true)
+    if [ -z $SHA ]; then
+        echo "Invalid source: '$SOURCE'"
+        exit 17
+    elif [ "$SOURCE" == "$SHA" ]; then
+        echo "Using $SHA as the source"
+    else
+        echo "Using '$SOURCE' ($SHA) as the source"
+    fi
+fi
+
 
 RC_BRANCH=stages/rc-$(date +'%Y-%m-%d')
 echo "Preparing RC branch ${RC_BRANCH}..."
